In [2]:
import numpy as np

In [4]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape (2,2,2)

In [5]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a1[-1]

9

In [10]:
a1[0]

0

In [11]:
a1[4]

4

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[1,0]

4

In [14]:
a2[2,3]

11

In [15]:
a2[0,2]

2

In [16]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a3[0,1,0]

2

In [18]:
a3[1,0,1]

5

In [19]:
a3[1,1,0]

6

In [32]:
#Slicing

In [33]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1[2:6]

array([2, 3, 4, 5])

In [35]:
a1[1:9:2]

array([1, 3, 5, 7])

In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a2[:,2]

array([ 2,  6, 10])

In [38]:
a2[:,1]

array([1, 5, 9])

In [40]:
a2[1,:]

array([4, 5, 6, 7])

In [42]:
a3 = np.arange(27).reshape(3,3,3)

In [43]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
a3[1:3]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [46]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [47]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
a3[1,0,:]

array([ 9, 10, 11])

In [49]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
a3[2,:,1]

array([19, 22, 25])

In [52]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])